config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments do
      member do
        post :publish
      end
    end
  end

  root 'posts#index'

  resources :authors, only: %i[new create] do
    get :profile, on: :collection
    patch :save_profile, on: :collection
  end

  post 'vote', to: 'votes#vote'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_secure_password

  has_many :posts
  has_many :comments
  has_many :author_comment_votes

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  validates :password, presence: true, length: { minimum: 6, maximum: 50 }, unless: :persisted?
  validates :email, presence: true, length: {
    minimum: 5, maximum: 50
  }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  def full_name
    "#{first_name} #{last_name} "
  end
end

app/models/author_comment_vote.rb
class AuthorCommentVote < ApplicationRecord
  belongs_to :comment
  belongs_to :author

  scope :liked, -> {where(positive: true)}
  scope :disliked, -> {where(positive: false)}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, required: true, counter_cache: true
  belongs_to :author, required: true
  has_many :author_comment_votes
  has_ancestry

  enum status: %i[unpublished published]

  validates :body, presence: true
  validates :body, length: { minimum: 5 }
  validates_with Validators::DepthValidator


  def count_likes
    self.author_comment_votes.liked.count
  end

  def count_dislikes
    self.author_comment_votes.disliked.count
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :comments, dependent: :destroy
  has_rich_text :content

  validates :name, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :title, length: { maximum: 100, message: 'is too long' }

  before_save do
    self.text = content.body.to_plain_text if content
  end

  def self.search(pattern)
    if pattern.blank?
      all
    else
      where('title ILIKE ? or text ILIKE ?', "%#{pattern}%", "%#{pattern}%")
    end
  end
end

app/models/validators/depth_validator.rb
module Validators
  class DepthValidator < ActiveModel::Validator
    def validate(record)
      if record.depth > 4
        record.errors.add :depth, "too deep"
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_author
  helper_method :logged_in?

  def current_author
    Author.find_by(id: session[:author_id])
  end

  def logged_in?
    !current_author.nil?
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @author = Author.new
  end

  def create
    @author = Author.create(author_auth_params)
    session[:author_id] = @author.id
    if @author.valid?
      redirect_to :root
    else
      redirect_to '/authors/new', alert: 'Invalid email or password'
    end
  end

  def profile
    @author = current_author
  end

  def save_profile
    current_author.update(author_params)
    redirect_to profile_authors_path
  end

  private

  def author_params
    params.require(:author).permit(:avatar, :first_name, :last_name)
  end

  def author_auth_params
    params.require(:author).permit(:email, :password)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :init_post
  before_action :init_comment, only: %i[destroy update]

  def create
    @comment = @post.comments.create(comment_params.merge(author_id: current_author.id))
    message = if @comment.persisted?
                { notice: 'Commented created successfully' }
              else
                { alert: 'Comment was not created. Make sure your comment is not less then 5 chars and it is not to deep' }
              end
    redirect_to post_path(@post), message
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post)
  end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@post), notice: 'Comment was successfully updated.'
    else
      redirect_to post_path(@post)
    end
  end

  # def publish
      #@post = Post.find(params[:post_id])
      #@comment = @post.comments.find(params[:id])
      #@comment.update(status: :published)
      #redirect_to post_path(@post), notice: 'Comment was successfully published.'
   #end

  private

  def comment_params
    params.require(:comment).permit(:body, :parent_id)
  end

  def init_post
    @post = Post.find(params[:post_id])
  end

  def init_comment
    @comment = @post.comments.where(author_id: current_author.id).find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_public_post, only: %i[show]
  before_action :set_author_post, only: %i[edit update destroy]
  before_action :add_view, only: %i[index show]

  def index
    @posts = Post.search(params[:q]).page params[:page]
  end

  def show
    # @comment_status = params[:comments_status].to_s.downcase

    #@comments = if @comment_status == 'unpublished'
                # @post.comments.unpublished
                #else
                #@post.comments.published
                #end
    @comments = @post.comments.all
    @post.update_columns(views_count: @post.views_count.to_i.succ)
    @post.increment!(:views_count)

  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params.merge(author_id: current_author.id))
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def set_public_post
    @post = Post.find(params[:id])
  end

  def set_author_post
    @post = Post.where(author_id: current_author.id).find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name, :title, :content, :image)
  end

  def add_view
    unless current_author
      cookies[:views] = cookies[:views].present? ? cookies[:views].to_i + 1 : 1
      @show_register = cookies[:views].to_i % 5 == 0
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @author = Author.find_by(email: params[:email])
    if @author && @author.authenticate(params[:password])
      session[:author_id] = @author.id
      redirect_to :root
    else
      redirect_to login_path, alert: 'Invalid email or password'
    end
  end

  def destroy
    session[:author_id] = nil
    redirect_to :root
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def vote
    vote_params = permitted_vote_params.merge(author_id: current_author.id)
    @vote = AuthorCommentVote.find_by(vote_params.except(:positive))

    if @vote.present?
      is_identical = @vote.positive?.to_s ==  vote_params[:positive]
      @vote.destroy
      @vote = AuthorCommentVote.create(vote_params) unless is_identical
    else
      @vote =  AuthorCommentVote.create(vote_params)
    end
    @post = @vote.comment.post
    @comments = @post.comments.to_a
    render "posts/show"
  end

  private

  def permitted_vote_params
    params.permit(:comment_id, :positive)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/authors/_avatar.erb
<%if author.avatar.present?%>
  <div>
    <img src='<%= author.avatar %>' width='200px'/>
  </div>
<% else %>
  <div>
    <img src='/ava.png' width='200px'/>
  </div>
<% end %>

app/views/authors/new.erb
<div class='cont'>
  <h2>Sign Up</h2>
  <%= form_for @author do |f|%>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %><br>
      <i style='color: gray'>it shold be like <b>smth@domain.com</b></i>
    </div>
    <div class="field">
      <%= f.label :password%><br>
      <%= f.password_field :password%><br>
      <i style='color: gray'>it shold be more then <b>6</b> symbols</i>
    </div>
    <div class="actions ">
      <%= f.submit 'Sign up', class: "btn btn-success" %>
    </div>
  <%end%>
</div>

app/views/authors/profile.erb
<div class='cont'>
  <%= form_with model: @author, url: save_profile_authors_path do |form| %>
    <%= render "authors/avatar", author: @author %>
    <div class="field">
      <%= form.label :avatar%>
      <%= form.text_field :avatar, class: 'form-control', rows: "3"%>
      <i style="color: gray">put a link to your avatar here</i>
    </div>
    <div class="field">
      <%= form.label :first_name%>
      <%= form.text_field :first_name, class: 'form-control', rows: "3"%>
    </div>     
    <div class="field">
      <%= form.label :last_name%>
      <%= form.text_field :last_name, class: 'form-control', rows: "3"%>
    </div>
    <div class="actions " >
      <%= form.submit 'Update profile', class: "btn btn-success"%>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs="
    crossorigin="anonymous"></script>
</head>

<body>
<div class="jumbotron jumbotron-fluid header">
  <div class="container">
    <div class='left'>Welcome to our little blog!</div>
    <% if logged_in? %>
      <div class='right'>&#9998;<%= link_to 'New Post', new_post_path %> </div>
      <div class='right'>&#9825; <%= link_to 'Home', posts_path %></div>
      <div class='right'>&#9734;<%= link_to 'Log out', logout_path, method: :delete %></div>
      <div class='right'><%= link_to "#{current_author.email}", '/authors/profile', method: :get %></div>
    <% else %>
      <div class='right'><%= link_to "Log in", '/login', method: :get%></div>
      <div class='right'><%= link_to "Sign Up", '/authors/new', method: :get%></div>
    <%end%>
  </div>
</div>
<div class='cont'>
  <p id="notice"><%= notice %></p>
  <p id="alert"><%= alert %></p>
</div>
<%= yield %>
</body>
</html>

app/views/posts/_comment_form.erb
<% comment ||= @post.comments.build%>
<div class='comment_form'>
  <%= form_with model: [ @post, comment ], local: false  do |form| %>
    <div class="field">
      <%= form.text_area :body, class: 'form-control', rows: "3"%>
    </div>
    <%= form.hidden_field :parent_id, value: parent_comment&.id %>
    <div class="actions " >
      <%= form.submit nil, class: "btn btn-success"%>
    </div>
  <% end %>
</div>

app/views/posts/_comment_one.erb
<div class='comment <%= "hidden_c" if comment.parent.present? %>'>
  <div class='comment_ava float'>
    <%= render "authors/avatar", author: comment.author %>
  </div>
  <div class='float'>
      <b><%= comment.author.email || comment.author.full_name %></b>
  </div>
  <div id="comment_<%= comment.id%>" class='full'>
      <button name='true' data-comment_id="<%= comment.id%>" class='like vote btn btn-outline-success'><i class='fa fa-thumbs-up'></i></button>
      <i><%= comment.count_likes %></i>&nbsp;
      <button name= 'false' data-comment_id="<%= comment.id%>" class='dislike vote btn btn-outline-danger'><i class='fa fa-thumbs-down'></i></button>
      <i><%= comment.count_dislikes %></i>&nbsp;|
      <%if comment.created_at < comment.updated_at%><b>edited</b> |<%end%>
      <% less_than_hour = comment.created_at >= 1.hour.ago %>
      <% time = distance_of_time_in_words(comment.created_at, Time.now)%>
      <span class='block'><i> created  <%= time  %> ago</i></span>
  </div>
  <div class='comment_body'>
    <%= comment.body %>
  </div>    
    <% if logged_in? && current_author.id == comment.author.id && less_than_hour %>
      <span class='comment_form_parent'>   
        <i class='fa fa-pencil-square-o btn btn-warning edit_comment'></i>
        <div class='cont add_comment update_comment invisible'>
          <h6>Edit Comment</h6>
          <%= render 'posts/comment_form', comment: comment, parent_comment: comment.parent%>
        </div>          
      <!--<% if comment.status == 'unpublished' %>
        <div class='btn btn-primary'>
          <%= link_to 'Publish Comment', publish_post_comment_path(@post.id, comment.id), method: :post %>
        </div>
      <% end %> -->
        <i class='btn btn-danger fa fa-trash-o'>
          <%= link_to 'remove', [comment.post, comment],
                    method: :delete,
                    data: { confirm: "Are you sure?" }, remote: true %>
        </i>
      </span>
    <% end %>
    
    <% if logged_in? && comment.depth < 4  %>
    <span class='comment_form_parent'>
    <span class='reply edit_comment'>Reply</span>
    <div class='cont add_comment update_comment invisible'>
        <br/>
        <%= render 'posts/comment_form', parent_comment: comment%>
      </div>
    </span>
    <%end%>

    <% if comment.children.present? %>
      <i class='fa fa-chevron-down open_children'></i>
      <% comment.children.each do |child| %>   
          <%= render 'posts/comment_one', comment: child%>
      <% end %>  
    <% end %>

</div>

app/views/posts/_comments_list.erb
<script>
  $(function(){
    /*$("#comments_select").change(function(){
      $('#comments_show').submit()
    })*/
     $(".edit_comment").click(function(){
      var $parent = $(this).parent('.comment_form_parent');
      var $comment = $parent.find('.update_comment');
      var $button = $(this);
      console.log($parent, $comment, $button)
      $comment.removeClass("invisible")
      $button.addClass('invisible')
    })
  })
</script>

<!--<form action="<%= post_path(@post) %>" method='get' id='comments_show'>
  <div class='field'>
    <select name='comments_status' class='btn btn-primary' id='comments_select'>
      <option <%= @comment_status == 'published' ? 'selected' : '' %> >Published</option>
      <option <%= @comment_status == 'unpublished' ? 'selected' : '' %> >Unpublished</option>
    </select> 
  </div>
</form> -->

<% @comments.select(&:root?).each do |comment| %>
  <br/>
    <%= render 'posts/comment_one', comment: comment%>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b><%= form.label :title %></b>
    <%= form.text_field :title, class: 'form-control'%>
  </div>

  <div class="field">
    <b> <%= form.label :name, 'Description'%></b>
    <%= form.text_field :name, class: 'form-control'%>
  </div>


  <div class="field">
    <b><%= form.label :content %></b>
    <%= form.rich_text_area :content %>
  </div>

  <div class="field">
    <b><%= form.label :image %></b>
    <%= form.text_field :image, class: 'form-control'  %>
  </div>

  <div class="actions " >
    <%= form.submit nil, class: "btn btn-success"%>
  </div>
<% end %>

app/views/posts/_modal.erb
<% if @show_register %>
  <script>
    $(function(){   
      $(".modal_login").show()           
      $('.close').click(function(){
        $(".modal_login").css("display", "none")
      }); 
    })
  </script>
  
  <div class="modal modal_login" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Hi. Let's be clother?</h5>
          <button type="button" class="close btn btn-danger" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Maybe you wanna login or sign up to have access to all features?</p>
        </div>
        <div class="modal-footer">
          <div class='btn btn-primary'><%= link_to "Log in", '/login', method: :get%></div>
          <div class='btn btn-primary'><%= link_to "Sign Up", '/authors/new'%></div>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/posts/_search_form.erb
<form class="form-inline row search" action="<%= posts_path %>" method='get'>
    <input class=" col-sm-4 search_imp" type="search" placeholder="Search" aria-label="Search" name='q' value="<%= params[:q] %>">
    <div class="col-sm-1"></div>
    <button class="btn btn-outline-primary col-sm-2 search_btn" type="submit">Search</button>
</form>

app/views/posts/edit.html.erb
<div class='cont'>
  <h2>Editing Post</h2>

  <%= render 'form', post: @post %>

  <div class='btn btn-primary'><%= link_to 'Show', @post %></div>
</div>

app/views/posts/index.html.erb
<script>
    $(function(){
        $(".clickable").click(function(e){
            var url = $(this).find('a').attr("href")
            $(location).attr('href',url);
        });
    })
</script>

<div class='container container_index'>
  <%= render 'posts/modal'%>
  <%= render 'posts/search_form'%>
  <p id="notice"><%= notice %></p>
  <% @posts.each do |post| %>
    <div class='row clickable'>
      <div class= "col-sm-2 column"><%= link_to "#{post.title} ", post, class: "link"%></div>
      <div class='col-sm-3 column'><%= post.author.email || post.author.full_name%>
        <%= render "authors/avatar", author: post.author %></div>
      <div class='col-sm-7 column'><%= post.text[0..500] + '...' %></div>
    </div>
  <% end %>

</div>

app/views/posts/new.html.erb
<div class='cont'>
  <h2>New Post</h2>
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class='cont show_post'>
  <%= render 'posts/modal'%>
  <div>
    <h4><b><%= @post.title %></b></h4>
  </div>
  <div>
    <img src='<%= @post.image %>' width='200px'/>
  </div>
  <div>
    <h5 class='h5_c'><%= @post.name %></h5>
  </div>
  <div>
    <p><%= @post.content %></p>
  </div><br/>
  <div class='show_post_author'>
    <%= render "authors/avatar", author: @post.author %>
    <i><b><%= @post.author.email || @post.author.full_name %></b></i>
  </div><br/>
  <div style="background: #fef7ff;" class='row'>
    <div class='col-sm-2'><i> <i class='fa fa-clock-o'></i> &nbsp;<%= distance_of_time_in_words(@post.updated_at, Time.now) %> ago</i></div>
    <div class='col-sm-2'><i><i class='fa fa-eye'></i> &nbsp; <%= @post.views_count %> </i></div>
    <div class='col-sm-2'><i><i class='fa fa-comments'></i> &nbsp;	<%= @post.comments_count || 0 %> <%= @post.comments_count != 1 ? ' comments' : ' comment' %></i></div>  
  </div>
  <br/>
    <%if logged_in? && current_author.id == @post.author.id %>
      <div class='btn btn-warning'><%= link_to 'Edit', edit_post_path(@post) %></div> 
      <div class='btn btn-danger'><%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %></div>
    <%end%>
  <div class='btn btn-primary'><%= link_to 'Back', posts_path %></div>
</div>
<div class='cont add_comment'>
  <br/>
  <% if logged_in? %>   
    <h4>New Comment</h4>
    <%= render 'posts/comment_form', parent_comment: nil %>
  <% else %>
    <h6>Please, <%= link_to "Log in", '/login', method: :get%> or <%= link_to "Sign Up", '/authors/new'%> to leave a comment</h6>
  <% end %>
</div>
<div class='cont comment_list'>
  <br/>
  <h4>Comments</h4>
  <br/> 
  <%= render 'posts/comments_list' %>
</div>